### ISSUE TITLE
Rouge Lair Boss Bug

### ISSUE THREAD

**Issue by RioNight** [FirehawkV21/ImmortalSins#1]
Describe bug:

Nothing happens when you interact with the boss in Rouge Lair after you fight his possesed Slimes.
(He was first sitting on the chair).

Version:
Latest version of Windows 10 Store

**Screenshots**
![image](https://user-images.githubusercontent.com/58403689/69921008-ee3c6d00-1453-11ea-8426-091be01ec5cb.png)

**Comment by FirehawkV21** [comment]
Well... The boss wasn't supposed to spawn yet until a bounty was received from Celtia's guild. The slimes were placeholder until I had the actual boss ready. I have it fixed now, alongside adding him in. He'll be in the next update. Closing this for now.
