### ISSUE TITLE
Entering Celtia Bar Bug 

### ISSUE THREAD

**Issue by RioNight** [FirehawkV21/ImmortalSins#2]
Description:

Player got stuck (at the bottom of the screen in the image) when entering the bar in Celtia Port.

Version: 
Latest Windows 10 Store Version 

Image: 
![image](https://user-images.githubusercontent.com/58403689/69922678-04522980-1464-11ea-95cb-ca9cedb46cb2.png)

**Comment by FirehawkV21** [comment]
Looking at the code, this bug happens when you return back to the port to get the boat. Fixed the bug now. The fix will roll out in the next update.

If you need the save file fixed, let me know.

Closing this.
