### ISSUE TITLE
Slime Hunt Guild Mission Bug 

### ISSUE THREAD

**Issue by RioNight** [FirehawkV21/ImmortalSins#3]
Description:

Groups of slime killed never increase on the objectives in the guild mission 'Sime Hunt'. 

Version:

Latest Windows 10 Version 

Image:

![image](https://user-images.githubusercontent.com/58403689/69922816-154f6a80-1465-11ea-8aea-b3a4164102fc.png)

**Comment by FirehawkV21** [comment]
Yeah. I found out why. The game had a bug where the necessary flag (that started counting the slimes) didn't apply. So, the game didn't count the slimes. I have it fixed in an upcoming build.

Closing this issue.
