### ISSUE TITLE
game bug found

### ISSUE THREAD

**Issue by benos21** [FirehawkV21/ImmortalSins#4]
I got a missing file [Fixed]Commanders Office. Can't go no further.

**Comment by FirehawkV21** [comment]
Hello.

What version of the game do you have? Maybe this is fixed in the latest version.

**Comment by benos21** [comment]
It’s Version D0.31 (0.31.0-20200420)

**Comment by FirehawkV21** [comment]
Hmm... Could you tell me what did you do to trigger the bug? That would help me diagnose the bug.

**Comment by benos21** [comment]
i was moving around or going to speak with the Commander in Corsair
[FIXED]Commander's Office.png failed to load.

**Comment by FirehawkV21** [comment]
Well... It's been a while, but I have fixed that issue in more recent versions of the game.
